services:
  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: myminiosecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO service port
      - "9001:9001"  # MinIO console port
    volumes:
      - ./data/minio:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio myminiosecret;
      /usr/bin/mc mb myminio/warehouse;
      exit 0;
      "

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: postgres  # Database name
      POSTGRES_USER: postgres  # Database user
      POSTGRES_PASSWORD: mypostgrespassword
    ports:
      - "5432:5432"  # Expose Postgres port
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties
